#merge from nest (version)
#change loki.dist => loki
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Grafana
      url: https://github.com/grafana/grafana
    - name: Loki
      url: https://github.com/grafana/loki
    - name: Mimir
      url: https://github.com/grafana/mimir
    - name: Tempo
      url: https://github.com/grafana/tempo
apiVersion: v2
appVersion: ^7.3.9
dependencies:
- alias: grafana
  condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 8.4.4
- name: loki
  version: 6.7.4
  repository: https://grafana.github.io/helm-charts
  condition: loki.enabled
- alias: mimir
  condition: mimir.enabled
  name: mimir-distributed
  repository: https://grafana.github.io/helm-charts
  version: 5.4.0
- alias: tempo
  condition: tempo.enabled
  name: tempo-distributed
  repository: https://grafana.github.io/helm-charts
  version: "^1.16.0"
- alias: grafana-oncall
  condition: grafana-oncall.enabled
  name: oncall
  repository: https://grafana.github.io/helm-charts
  version: ^1.3.114
description: Umbrella chart for a distributed Loki, Grafana, Tempo and Mimir stack
home: https://grafana.com/oss/
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
keywords:
- monitoring
- traces
- metrics
- logs
maintainers:
- name: timberhill
name: lgtm-distributed
sources:
- https://grafana.github.io/helm-charts
- https://github.com/grafana/grafana
- https://github.com/grafana/loki
- https://github.com/grafana/mimir
- https://github.com/grafana/tempo
type: application
version: 2.1.0
