{{- if .Values.namespaces }}
{{- range .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  {{- range $key, $value := .annotations }}
  annotations:
    {{$key }}: {{$value}}
  {{- end }}
  labels:
    kubernetes.io/metadata.name: {{ .name }}
    name: {{ .name }}
    {{- range $key, $value := .labels }}
    {{$key }}: {{$value}}
    {{- end }}
  name: {{ .name }}
---
{{- end}}
{{- end}}