apiVersion: v2
version: 0.1.0
appVersion: "1.16.0"
name: lgtm
description: "LGTM Stack"
type: application
kubeVersion: ^1.20.0-0
dependencies:
  - name: loki
    version: 6.7.4
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: grafana
    version: 8.4.4
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: tempo-distributed
    version: "^1.16.0"
    alias: tempo
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled
  - name: mimir-distributed
    alias: mimir
    version: 5.4.0
    repository: https://grafana.github.io/helm-charts
    condition: mimir.enabled
  - name: postgresql
    alias: postgresql
    condition: postgresql.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "^15.5.20"