apiVersion: v2
appVersion: 0.0.1
dependencies:
- condition: local.logs.enabled
  name: loki
  repository: https://grafana.github.io/helm-charts
  version: 6.5.2
- name: alloy
  repository: https://grafana.github.io/helm-charts
  version: 0.2.0
- condition: local.metrics.enabled
  name: mimir-distributed
  repository: https://grafana.github.io/helm-charts
  version: 5.3.0
- condition: local.traces.enabled
  name: tempo-distributed
  repository: https://grafana.github.io/helm-charts
  version: 1.9.9
- condition: local.minio.enabled
  name: minio
  repository: https://charts.min.io
  version: 5.2.0
description: from original 1.0.0
name: meta-monitoring
type: application
version: 1.0.1
